
Neos:
  Fusion:
    defaultContext:
      Twitter: FabianCernota\TwitterHelper\Eel\TwitterHelper
  Neos:
    fusion:
      autoInclude:
        FabianCernota.TwitterHelper: true
FabianCernota:
  TwitterHelper:
    oauthAccessToken: ''
    oauthAccessTokenSecret: ''
    consumerKey: ''
    consumerSecret: ''
